(defun start ()
  (setq *goal-pt* (@ 1 1))
  (setq *C-arrow* 4)
  (setq *respawn-rate* 4)
  (setq *max-jugs* 2)
  (reset)
  (run-environment (make-our-world :size (@ 6 6)
				   :aspec '((at (2 3) B)
					    (at (4 3) B)
					    (at (4 3) B)
					    (at (3 2) B)
					    (at (2 1) B)
					    (at (1 3) C)
					    (at (1 1) A))
				   :bspec '((at edge wall)
					    (at (4 3) gold))
				   :max-steps 11)))
